# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),debug)
  CSC = mcs
  RESGEN = resgen
TARGETDIR = ../../build/testing/managed/Debug-linux
TARGET = $(TARGETDIR)/ExampleGameTests.exe
OBJDIR = ../../build/testing/managed/Debug-linux/Intermediates/Debug
  FLAGS = /noconfig -sdk:4.7.2
  DEPENDS =
  REFERENCES = 
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef
endif

ifeq ($(config),release)
  CSC = mcs
  RESGEN = resgen
TARGETDIR = ../../build/testing/managed/Debug-linux
TARGET = $(TARGETDIR)/ExampleGameTests.exe
OBJDIR = ../../build/testing/managed/Debug-linux/Intermediates/Release
  FLAGS = /optimize /noconfig -sdk:4.7.2
  DEPENDS =
  REFERENCES = 
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef
endif

FLAGS += /t:exe 
REFERENCES += /r:System

SOURCES += \
	../../examples/Skybound/Assets/Scripts/Source/Flight.cs \
	FlightTests.cs \

EMBEDFILES += \

RESPONSE += $(OBJDIR)/ExampleGameTests.rsp
SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

all: prebuild $(EMBEDFILES) $(COPYFILES) $(TARGET)

$(TARGET): $(SOURCES) $(EMBEDFILES) $(DEPENDS) $(RESPONSE) | $(TARGETDIR)
	$(PRELINKCMDS)
	$(SILENT) $(CSC) /nologo /out:$@ $(FLAGS) $(REFERENCES) @$(RESPONSE) $(patsubst %,/resource:%,$(EMBEDFILES))
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR)) 2>nul || if exist $(subst /,\\,$(TARGETDIR))\\NUL (exit /b 0) else (exit /b 1)
endif

$(RESPONSE): ExampleGameTests.make
	@echo Generating response file
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f $(RESPONSE)
else
	$(SILENT) if exist $(RESPONSE) del $(OBJDIR)\ExampleGameTests.rsp
endif
	@echo ../../examples/Skybound/Assets/Scripts/Source/Flight.cs >> $(RESPONSE)
	@echo FlightTests.cs >> $(RESPONSE)

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR)) 2>nul || if exist $(subst /,\\,$(OBJDIR))\\NUL (exit /b 0) else (exit /b 1)
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)
